server:
  port: 9401
spring:
  application:
    name: tensquare-base
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.153:8306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
#   rabbitmq:
#     host: 192.168.129.130
#    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
ip: 123:123:123:123
